# Generated by Django 4.2.9 on 2024-04-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VER', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificaciones',
            options={'verbose_name': 'Calificacion', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='categoriascalificacion',
            options={'verbose_name': 'Categoriascalificacion', 'verbose_name_plural': 'CategoriasCalificaciones'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='comunidades',
            options={'verbose_name': 'Comunidad', 'verbose_name_plural': 'Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='comunidadesusuario',
            options={'verbose_name': 'ComunidadesUsuario', 'verbose_name_plural': 'ComunidadesUsuarios'},
        ),
        migrations.AlterModelOptions(
            name='dias',
            options={'verbose_name': 'Dia', 'verbose_name_plural': 'Dias'},
        ),
        migrations.AlterModelOptions(
            name='diasrutas',
            options={'verbose_name': 'DiasRuta', 'verbose_name_plural': 'DiasRutas'},
        ),
        migrations.AlterModelOptions(
            name='ordentrayectoria',
            options={'verbose_name': 'OrdenTrayectoria', 'verbose_name_plural': 'OrdenTrayectorias'},
        ),
        migrations.AlterModelOptions(
            name='ordentrayectoriareal',
            options={'verbose_name': 'OrdenTrayectoriaReal', 'verbose_name_plural': 'OrdenTrayectoriasReales'},
        ),
        migrations.AlterModelOptions(
            name='recepcionpasajeros',
            options={'verbose_name': 'RecepcionPasajero', 'verbose_name_plural': 'RecepcionPasajeros'},
        ),
        migrations.AlterModelOptions(
            name='recepecionreal',
            options={'verbose_name': 'RecepecionReal', 'verbose_name_plural': 'RecepcionesReales'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolusuario',
            options={'verbose_name': 'RolUsuario', 'verbose_name_plural': 'RolUsuarios'},
        ),
        migrations.AlterModelOptions(
            name='rutas',
            options={'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AlterModelOptions(
            name='rutasejecutadas',
            options={'verbose_name': 'RutaEjecutada', 'verbose_name_plural': 'RutasEjecutadas'},
        ),
        migrations.AlterModelOptions(
            name='trayectoria',
            options={'verbose_name': 'Trayectoria', 'verbose_name_plural': 'Trayectorias'},
        ),
        migrations.AlterModelOptions(
            name='trayectoriareal',
            options={'verbose_name': 'TrayectoriaReal', 'verbose_name_plural': 'TrayectoriasReales'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='vehiculos',
            options={'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
        migrations.AlterModelOptions(
            name='vehiculousuario',
            options={'verbose_name': 'VehiculoUsuario', 'verbose_name_plural': 'VehiculoUsuarios'},
        ),
    ]
