# Generated by Django 4.2.9 on 2024-04-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VER', '0002_alter_calificaciones_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.CharField(default='', max_length=30, verbose_name='Edad del usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='Correo electronico'),
        ),
    ]
