# Generated by Django 4.2.9 on 2024-04-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VER', '0003_usuario_edad_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='Correo electronico'),
        ),
    ]
