# Generated by Django 4.2.9 on 2024-04-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VER', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(default='', max_length=30, verbose_name='Sexo del usuario'),
        ),
    ]
