# Generated by Django 4.2.9 on 2024-04-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la calificacion')),
                ('comentario', models.TextField(max_length=500, verbose_name='Comentarios de la calificacion')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la calificacion')),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Comunidades',
            fields=[
                ('id_comunidad', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la comunidad')),
                ('nombre_comunidad', models.CharField(max_length=100, verbose_name='Nombre de la comunidad')),
                ('comuna', models.CharField(max_length=50, verbose_name='Nombre de la comuna')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registro de creacion')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id_dia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del dia de la semana')),
                ('nombre_dia', models.CharField(max_length=10, verbose_name='Nombre el dia de la semana')),
            ],
            options={
                'verbose_name': 'Dia',
                'verbose_name_plural': 'Dias',
            },
        ),
        migrations.CreateModel(
            name='RecepcionPasajeros',
            fields=[
                ('id_recepcion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del a recepcion')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registro del momento el recepcion')),
            ],
            options={
                'verbose_name': 'RecepcionPasajero',
                'verbose_name_plural': 'RecepcionPasajeros',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del rol')),
                ('nombre_rol', models.CharField(max_length=30, verbose_name='Nombre del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la ruta')),
                ('nombre_ruta', models.CharField(max_length=50, verbose_name='Nombre de la ruta')),
                ('origen', models.CharField(max_length=30, verbose_name='Origen de la ruta')),
                ('destino', models.CharField(max_length=30, verbose_name='Destino de la ruta')),
                ('hora_salida', models.CharField(max_length=10, verbose_name='Hora de salida de la ruta')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion de ruta')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del usuario')),
                ('nombre_usuario', models.CharField(max_length=100, verbose_name='Nombre del usuario')),
                ('apellido_usuario', models.CharField(max_length=100, verbose_name='Apellido del usuario')),
                ('edad', models.CharField(default='', max_length=30, verbose_name='Edad del usuario')),
                ('sexo', models.CharField(default='', max_length=30, verbose_name='Sexo del usuario')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Correo electronico')),
                ('clave', models.CharField(max_length=50, verbose_name='Password')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono del usuario')),
                ('descripcion_usuario', models.TextField(max_length=500, verbose_name='Descripcion del usuario')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registro de creacion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del vehiculo')),
                ('marca_vehiculo', models.CharField(max_length=50, verbose_name='Marca del vehiculo')),
                ('modelo_vehiculo', models.CharField(max_length=50, verbose_name='Modelo del vehiculo')),
                ('tipo_de_vehiculo', models.CharField(max_length=50, verbose_name='Tipo de vehiculo')),
                ('nro_asientos_disp', models.IntegerField(verbose_name='Numero de asientos disponibles')),
                ('color_vehiculo', models.CharField(max_length=20, verbose_name='Color del vehiculo')),
                ('patente', models.CharField(max_length=10, verbose_name='Patente del vehiculo')),
                ('ano_vehiculo', models.CharField(max_length=4, verbose_name='Año del vehiculo')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registro de creacion')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehiculoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.usuario', verbose_name='ID del usuario')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.vehiculos', verbose_name='ID del vehiculo')),
            ],
            options={
                'verbose_name': 'VehiculoUsuario',
                'verbose_name_plural': 'VehiculoUsuarios',
            },
        ),
        migrations.CreateModel(
            name='TrayectoriaReal',
            fields=[
                ('id_trayectoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la trayectoria')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion de trayectoria')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta')),
            ],
            options={
                'verbose_name': 'TrayectoriaReal',
                'verbose_name_plural': 'TrayectoriasReales',
            },
        ),
        migrations.CreateModel(
            name='Trayectoria',
            fields=[
                ('id_trayectoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la trayectoria')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion de trayectoria')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta')),
            ],
            options={
                'verbose_name': 'Trayectoria',
                'verbose_name_plural': 'Trayectorias',
            },
        ),
        migrations.CreateModel(
            name='RutasEjecutadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_inicio', models.BooleanField(verbose_name='Flag de inicio de la ruta')),
                ('inicio_real', models.DateTimeField(auto_now_add=True, verbose_name='Registro de la fecha del inicio real de al ruta')),
                ('id_conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.usuario', verbose_name='ID del usuario')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta')),
            ],
            options={
                'verbose_name': 'RutaEjecutada',
                'verbose_name_plural': 'RutasEjecutadas',
            },
        ),
        migrations.AddField(
            model_name='rutas',
            name='id_conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.usuario', verbose_name='ID del conductor'),
        ),
        migrations.AddField(
            model_name='rutas',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.vehiculos', verbose_name='ID del vehiculo'),
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.roles', verbose_name='ID del rol')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.usuario', verbose_name='ID del usuario')),
            ],
            options={
                'verbose_name': 'RolUsuario',
                'verbose_name_plural': 'RolUsuarios',
            },
        ),
        migrations.CreateModel(
            name='RecepecionReal',
            fields=[
                ('id_recepecion_real', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la recepcion real')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registro del momento el recepcion real')),
                ('id_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.usuario', verbose_name='ID del pasajero')),
                ('id_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.recepcionpasajeros', verbose_name='ID de la recepcion')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta')),
            ],
            options={
                'verbose_name': 'RecepecionReal',
                'verbose_name_plural': 'RecepcionesReales',
            },
        ),
        migrations.AddField(
            model_name='recepcionpasajeros',
            name='id_pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.usuario', verbose_name='ID del pasajero'),
        ),
        migrations.AddField(
            model_name='recepcionpasajeros',
            name='id_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta'),
        ),
        migrations.CreateModel(
            name='OrdenTrayectoriaReal',
            fields=[
                ('id_trayec_real', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la trayectoria real')),
                ('orden_real', models.IntegerField(verbose_name='Orden real de la trayectoria')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('id_trayectoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.trayectoriareal', verbose_name='ID de trayectoria')),
            ],
            options={
                'verbose_name': 'OrdenTrayectoriaReal',
                'verbose_name_plural': 'OrdenTrayectoriasReales',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrayectoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(verbose_name='Orden de la trayectoria')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('id_trayectoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.trayectoria', verbose_name='ID de la trayectoria')),
            ],
            options={
                'verbose_name': 'OrdenTrayectoria',
                'verbose_name_plural': 'OrdenTrayectorias',
            },
        ),
        migrations.CreateModel(
            name='DiasRutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.dias', verbose_name='ID del dia de la semana')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta')),
            ],
            options={
                'verbose_name': 'DiasRuta',
                'verbose_name_plural': 'DiasRutas',
            },
        ),
        migrations.CreateModel(
            name='ComunidadesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.comunidades', verbose_name='ID de la comunidad')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.usuario', verbose_name='ID del usuario')),
            ],
            options={
                'verbose_name': 'ComunidadesUsuario',
                'verbose_name_plural': 'ComunidadesUsuarios',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del mensaje')),
                ('mensaje', models.TextField(verbose_name='Contenido del mensaje')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='marca de tiempo del mensaje')),
                ('id_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_enviado', to='DatabaseManager.usuario', verbose_name='ID del usuario emisor')),
                ('id_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensaje_recibido', to='DatabaseManager.usuario', verbose_name='ID del usuario receptor')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='CategoriasCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguridad', models.IntegerField(verbose_name='Seguridad del viaje')),
                ('limpieza', models.IntegerField(verbose_name='Limpieza del vehiculo')),
                ('comodidad', models.IntegerField(verbose_name='Comodidad del viaje')),
                ('puntualidad', models.IntegerField(verbose_name='Puntualidad del conductor')),
                ('id_calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.calificaciones', verbose_name='ID de la calificacion')),
            ],
            options={
                'verbose_name': 'Categoriascalificacion',
                'verbose_name_plural': 'CategoriasCalificaciones',
            },
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='id_calificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calficacion_recibida', to='DatabaseManager.usuario', verbose_name='ID del usuario calificado'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='id_calificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calficacion_realizada', to='DatabaseManager.usuario', verbose_name='ID del usuario calificador'),
        ),
    ]
