# Generated by Django 4.2.9 on 2024-04-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriascalificacion',
            old_name='id_calificador',
            new_name='id_calificacion',
        ),
    ]
