# Generated by Django 5.0.4 on 2024-06-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0004_alter_usuario_apellido_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', verbose_name='Imagen de perfil Usuarios'),
        ),
    ]
