# Generated by Django 5.0.4 on 2024-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0005_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo/', verbose_name='Imagen de perfil vehiculo'),
        ),
    ]
