# Generated by Django 5.0.4 on 2024-08-20 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0006_vehiculos_imagen_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la comuna')),
                ('nombre_comuna', models.CharField(max_length=50, verbose_name='Nombre de la comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Región')),
                ('nombre_region', models.CharField(max_length=50, verbose_name='Nombre de la región')),
            ],
        ),
        migrations.RemoveField(
            model_name='comunidades',
            name='comuna',
        ),
        migrations.CreateModel(
            name='ComunaComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.comuna', verbose_name='ID de la comuna')),
                ('id_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.comunidades', verbose_name='ID de la comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='ComunaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.comuna', verbose_name='ID de la comuna')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.region', verbose_name='ID de la region')),
            ],
        ),
    ]
