# Generated by Django 5.0.4 on 2024-09-25 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0008_alter_comuna_options_alter_comunacomunidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='latitud',
            field=models.FloatField(default=0, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='longitud',
            field=models.FloatField(default=0, verbose_name='Longitud'),
        ),
        migrations.CreateModel(
            name='ComunaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.comuna', verbose_name='ID de la comuna')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID del usuario')),
            ],
            options={
                'verbose_name': 'ComunaUsuario',
                'verbose_name_plural': 'ComunaUsuario',
            },
        ),
    ]
