# Generated by Django 5.0.4 on 2024-10-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0009_comuna_latitud_comuna_longitud_comunausuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
