# Generated by Django 5.0.4 on 2024-10-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0011_comunidades_latitud_comunidades_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutasejecutadas',
            name='flag_inicio',
            field=models.BooleanField(default=False, verbose_name='Flag de inicio de la ruta'),
        ),
    ]
