# Generated by Django 5.0.4 on 2024-10-21 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0012_alter_rutasejecutadas_flag_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactosEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_emergencia', models.CharField(max_length=50, verbose_name='Correo de emergencia')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID del usuario')),
            ],
            options={
                'verbose_name': 'ContactoEmergencia',
                'verbose_name_plural': 'ContactosEmergencia',
            },
        ),
    ]
