# Generated by Django 5.0.4 on 2024-10-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0013_contactosemergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la notificacion')),
                ('leido', models.BooleanField(default=False)),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True)),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID del usuario')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
    ]
