# Generated by Django 5.0.4 on 2024-10-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0014_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='es_comunidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='es_ruta',
            field=models.BooleanField(default=False),
        ),
    ]
