# Generated by Django 5.0.4 on 2024-10-23 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0020_alter_notificaciones_id_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='id_propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario_ruta', to=settings.AUTH_USER_MODEL, verbose_name='ID propietario ruta o comunidad'),
        ),
    ]
