# Generated by Django 5.0.4 on 2024-10-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0022_alter_notificaciones_id_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutas',
            name='cupos',
            field=models.IntegerField(default=0, verbose_name='Cupos disponibles'),
            preserve_default=False,
        ),
    ]
