# Generated by Django 5.0.4 on 2024-10-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0023_rutas_cupos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificaciones',
            old_name='leido',
            new_name='aceptada',
        ),
    ]
