# Generated by Django 5.0.4 on 2024-10-24 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0024_rename_leido_notificaciones_aceptada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembrosComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True)),
                ('id_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.comunidades', verbose_name='ID de la comunidad')),
                ('id_miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID de miembro')),
            ],
            options={
                'verbose_name': 'MiembroComunidad',
                'verbose_name_plural': 'MiembrosComunidades',
            },
        ),
    ]
