# Generated by Django 5.0.4 on 2024-10-24 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0025_miembroscomunidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembrosRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True)),
                ('id_miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID de miembro')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID ruta')),
            ],
            options={
                'verbose_name': 'MiembroRuta',
                'verbose_name_plural': 'MiembrosRutas',
            },
        ),
    ]
