# Generated by Django 5.0.4 on 2024-10-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0028_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutasejecutadas',
            name='flag_inicio',
        ),
    ]
