# Generated by Django 5.0.4 on 2024-10-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0029_remove_rutasejecutadas_flag_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutasejecutadas',
            name='inicio_real',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Registro de la fecha del inicio real de al ruta'),
        ),
    ]
