# Generated by Django 5.0.4 on 2024-11-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0030_alter_rutasejecutadas_inicio_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcionpasajeros',
            name='id_pasajero',
        ),
        migrations.RemoveField(
            model_name='recepcionpasajeros',
            name='id_ruta',
        ),
        migrations.RemoveField(
            model_name='recepecionreal',
            name='id_recepcion',
        ),
        migrations.RemoveField(
            model_name='recepecionreal',
            name='id_pasajero',
        ),
        migrations.RemoveField(
            model_name='recepecionreal',
            name='id_ruta',
        ),
        migrations.RemoveField(
            model_name='trayectoriareal',
            name='id_ruta',
        ),
        migrations.DeleteModel(
            name='OrdenTrayectoriaReal',
        ),
        migrations.DeleteModel(
            name='RecepcionPasajeros',
        ),
        migrations.DeleteModel(
            name='RecepecionReal',
        ),
        migrations.DeleteModel(
            name='TrayectoriaReal',
        ),
    ]
