# Generated by Django 5.0.4 on 2024-11-10 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0032_remove_comuna_latitud_remove_comuna_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True)),
                ('id_denunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_denunciado', to=settings.AUTH_USER_MODEL, verbose_name='id del usuario denunciado')),
                ('id_denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_denunciante', to=settings.AUTH_USER_MODEL, verbose_name='id del usuario denunciante')),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
            },
        ),
    ]
