# Generated by Django 5.0.4 on 2024-11-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0033_denuncias'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncias',
            name='info_denuncia',
            field=models.TextField(default=None, max_length=1000, verbose_name='Info denuncia'),
        ),
    ]
