# Generated by Django 5.0.4 on 2024-11-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseManager', '0034_denuncias_info_denuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionPasajeros',
            fields=[
                ('id_recepcion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del a recepcion')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registro del momento el recepcion')),
                ('id_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID del pasajero')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta')),
            ],
            options={
                'verbose_name': 'RecepcionPasajero',
                'verbose_name_plural': 'RecepcionPasajeros',
            },
        ),
        migrations.CreateModel(
            name='RecepecionReal',
            fields=[
                ('id_recepecion_real', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la recepcion real')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registro del momento el recepcion real')),
                ('id_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID del pasajero')),
                ('id_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.recepcionpasajeros', verbose_name='ID de la recepcion')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta')),
            ],
            options={
                'verbose_name': 'RecepecionReal',
                'verbose_name_plural': 'RecepcionesReales',
            },
        ),
        migrations.CreateModel(
            name='TrayectoriaReal',
            fields=[
                ('id_trayectoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la trayectoria')),
                ('tiempo_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion de trayectoria')),
                ('id_ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.rutas', verbose_name='ID de la ruta')),
            ],
            options={
                'verbose_name': 'TrayectoriaReal',
                'verbose_name_plural': 'TrayectoriasReales',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrayectoriaReal',
            fields=[
                ('id_trayec_real', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la trayectoria real')),
                ('orden_real', models.IntegerField(verbose_name='Orden real de la trayectoria')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('id_trayectoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DatabaseManager.trayectoriareal', verbose_name='ID de trayectoria')),
            ],
            options={
                'verbose_name': 'OrdenTrayectoriaReal',
                'verbose_name_plural': 'OrdenTrayectoriasReales',
            },
        ),
    ]
